server:
   port: 8099

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    nonSecurePort: 8099

zuul:
  routes:
    backend:
      path: /backend/**
      url: http://localhost:8080/
    ribbonuser:
      path: /ribbonbackend/**
      serviceId: BACKEND

#ribbon:
#  eureka:
#    enabled: false

